kind: Pod
apiVersion: v1
metadata: 
  name: myvolemptydir
spec:
  containers:
    - name: c1
      image: centos
      command: ["/bin/bash","-c","sleep 10000"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/exchange"
    - name: c2
      image: centos
      command: ["/bin/bash","-c","sleep 10000"]
      volumeMounts:
        - name: xchange
          mountPath: "/tmp/data"
  volumes:
      - name: xchange
        emptyDir: {}