kind: Pod
apiVersion: v1
metadata:
  name: nodelabels
  labels:
    env: develop
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash","-c","while true;do echo We learn K8S; sleep5;done"]
  nodeSelector:
    owner: daman